### ISSUE TITLE
Lucius and Cassius `&` not documented

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [yesodweb/shakespeare#246]
The `&`, as in sass, allows nested classes for the same element selector.

```cassius
div
  .some-class
    font-size: 1em
  .some-other-class
    font-size: 2em
```
results in
```css
div.some-class {font-size: 1em;}
div.some-other-class {font-size: 2em;}
```
