### ISSUE TITLE
[lucius] @supports mixing problem?

### ISSUE THREAD

**Issue by jeongoon** [yesodweb/shakespeare#255]
```css
.status::before {
    content: 'CSS Parallax is: NOT SUPPORTED';
    color: #c00;
    display: block;

}

@supports ((perspective: 1px) and (not (-webkit-overflow-scrolling: touch))) {
    .status::before {
        content: 'CSS Parallax is: SUPPORTED';
        color: #090;
    }
}
```

I'm trying to apply css from "https://keithclark.co.uk/articles/practical-css-parallax/feature-detection/"
but lucius produced something I don't want
the result looks like:

```css
.status::before {
    content: 'CSS Parallax is: NOT SUPPORTED';
    color: #ccc
    display: block;
}
color: #090;
    }
}
```

I'm trying to avoid the what happened here. or should I put some css into "static" ?
