### ISSUE TITLE
Mixins should respect rule order

### ISSUE THREAD

**Issue by jezen** [yesodweb/shakespeare#262]
Given the following mixin

```haskell
redText :: Mixin
redText = [cassiusMixin|color: red|]

```

I would expect the following Cassius template

```cassius
.foo
  ^{redText}
  color: blue
```

to produce the following CSS:

```css
.foo {
  color: red;
  color: blue;
}
```

however, it actually produces this CSS:

```css
.foo {
  color: blue;
  color: red;
}
```

I _think_ that's because of [these lines](https://github.com/yesodweb/shakespeare/blob/master/Text/Internal/Css.hs#L374-L376).

I would rather using a mixin doesn't affect sort order, as sort order is important in CSS.
